---
ci:
  collect:
    numberOfRuns: 3
    staticDistDir: exampleSite/public
    url:
      - http://localhost/
      - http://localhost/404.html
      - http://localhost/posts/usage/getting-started/
    settings:
      chromeFlags: "--no-sandbox"
      skipAudits:
        - uses-long-cache-ttl
        - csp-xss
        # FIXME: https://github.com/GoogleChrome/lighthouse/issues/14957
        - bf-cache
        - is-crawlable
  assert:
    preset: "lighthouse:no-pwa"
    assertions:
      tap-targets: warn
      unsized-images: warn
      # FIXME: https://github.com/GoogleChrome/lighthouse/issues/11460
      categories:performance:
        - warn
        - minScore: 0.95
      categories:accessibility:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 0.95
  upload:
    target: filesystem
    outputDir: lhci_reports
